# Generated by Django 4.1.3 on 2024-05-13 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Опубликован или нет'),
        ),
    ]
