# Generated by Django 4.1.3 on 2024-05-12 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('discount_percentage', models.IntegerField(default=None, verbose_name='Процент скиндки (если есть)')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('stop', models.BooleanField(default=True, verbose_name='Находится ли в продаже')),
                ('nutritional_value', models.CharField(max_length=128, verbose_name='Пищевая ценность')),
                ('mass', models.CharField(blank=True, max_length=11, null=True, verbose_name='Масса')),
                ('volume', models.CharField(blank=True, max_length=11, null=True, verbose_name='Объем')),
                ('quantity', models.CharField(blank=True, max_length=11, null=True, verbose_name='Количество')),
                ('diameter', models.CharField(blank=True, max_length=11, null=True, verbose_name='Диаметр')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Категория')),
                ('promotion_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.promotion', verbose_name='Акция')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
